# Generated by Django 4.2 on 2023-05-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='updated date'),
        ),
    ]
