# Generated by Django 4.2 on 2023-05-23 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_report_author_report_post_author_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
