# Generated by Django 4.2 on 2023-05-23 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_delete_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=30, verbose_name='reason')),
                ('is_agreed', models.BooleanField(default=False, verbose_name='agree')),
                ('date_reported', models.DateTimeField(default=django.utils.timezone.now, verbose_name='reported date')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.post')),
                ('post_author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to=settings.AUTH_USER_MODEL)),
                ('report_author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='report_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
