# Generated by Django 4.2 on 2023-05-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='report_amount',
            field=models.IntegerField(default=0, verbose_name='count of report'),
        ),
        migrations.AddField(
            model_name='user',
            name='report_date',
            field=models.DateTimeField(null=True, verbose_name='time of report'),
        ),
    ]
